function [fm_names] = names()
% [fm_names] = names()
%

f_names1 = { ...
  'Anna','she','her','her'; ...
  'Beth','she','her','her'; ...
  'Carol','she','her','her'; ...
  'Diane','she','her','her'; ...
  'Ellen','she','her','her'; ...
  'Frances','she','her','her'; ...
  'Gail','she','her','her'; ...
  'Hilary','she','her','her'; ...
  'Isabel','she','her','her'; ...
  'Janet','she','her','her'; ...
  'Kathy','she','her','her'; ...
  'Laura','she','her','her'; ...
  'Mary','she','her','her'; ...
  'Nancy','she','her','her'; ...
  'Olivia','she','her','her'; ...
  'Pam','she','her','her'; ...
  'Quinn','she','her','her'; ...
  'Ruth','she','her','her'; ...
  'Sally','she','her','her'; ...
  'Tricia','she','her','her'; ...
  'Ursula','she','her','her'; ...
  'Veronica','she','her','her'; ...
  'Wendy','she','her','her'; ...
  'Xena','she','her','her'; ...
  'Yolanda','she','her','her'; ...
  'Zoey','she','her','her'; ...
};

f_names2 = {
  'Alice','she','her','her'; ...
  'Becky','she','her','her'; ...
  'Carly','she','her','her'; ...
  'Darcy','she','her','her'; ...
  'Edna','she','her','her'; ...
  'Fae','she','her','her'; ...
  'Gina','she','her','her'; ...
  'Heather','she','her','her'; ...
  'Ingrid','she','her','her'; ...
  'Jane','she','her','her'; ...
  'Kate','she','her','her'; ...
  'Leah','she','her','her'; ...
  'Megan','she','her','her'; ...
  'Nicole','she','her','her'; ...
  'Olive','she','her','her'; ...
  'Paige','she','her','her'; ...
  'Quianna','she','her','her'; ...
  'Rachel','she','her','her'; ...
  'Sarah','she','her','her'; ...
  'Tara','she','her','her'; ...
  'Uma','she','her','her'; ...
  'Vicky','she','her','her'; ...
  'Wanda','she','her','her'; ...
  'Xandra','she','her','her'; ...
  'Yasmin','she','her','her'; ...
  'Zola','she','her','her'; ...
};

f_names3 = {
  'Abby','she','her','her'; ...
  'Brenda','she','her','her'; ...
  'Cassie','she','her','her'; ...
  'Deana','she','her','her'; ...
  'Esther','she','her','her'; ...
  'Fiona','she','her','her'; ...
  'Greta','she','her','her'; ...
  'Haley','she','her','her'; ...
  'Iris','she','her','her'; ...
  'Jill','she','her','her'; ...
  'Kaylin','she','her','her'; ...
  'Leila','she','her','her'; ...
  'Maya','she','her','her'; ...
  'Naomi','she','her','her'; ...
  'Orly','she','her','her'; ...
  'Paula','she','her','her'; ...
  'Queenie','she','her','her'; ...
  'Regina','she','her','her'; ...
  'Sharon','she','her','her'; ...
  'Tabitha','she','her','her'; ...
  'Una','she','her','her'; ...
  'Valerie','she','her','her'; ...
  'Wilma','she','her','her'; ...
  'Xara','she','her','her'; ...
  'Yelena','she','her','her'; ...
  'Zara','she','her','her'; ...
};

m_names1 = { ...
  'Aaron','he','his','him'; ...
  'Brett','he','his','him'; ...
  'Carl','he','his','him'; ...
  'Daniel','he','his','him'; ...
  'Eric','he','his','him'; ...
  'Frank','he','his','him'; ...
  'Greg','he','his','him'; ...
  'Howard','he','his','him'; ...
  'Isaac','he','his','him'; ...
  'John','he','his','him'; ...
  'Kyle','he','his','him'; ...
  'Lance','he','his','him'; ...
  'Mark','he','his','him'; ...
  'Nathan','he','his','him'; ...
  'Owen','he','his','him'; ...
  'Paul','he','his','him'; ...
  'Quincy','he','his','him'; ...
  'Roger','he','his','him'; ...
  'Steven','he','his','him'; ...
  'Thomas','he','his','him'; ...
  'Ulric','he','his','him'; ...
  'Victor','he','his','him'; ...
  'Walter','he','his','him'; ...
  'Xavier','he','his','him'; ...
  'Yuri','he','his','him'; ...
  'Zane','he','his','him'; ...
};

m_names2 = { ...
  'Albert','he','his','him'; ...
  'Ben','he','his','him'; ...
  'Calvin','he','his','him'; ...
  'Dale','he','his','him'; ...
  'Earl','he','his','him'; ...
  'Fred','he','his','him'; ...
  'Gary','he','his','him'; ...
  'Hans','he','his','him'; ...
  'Ian','he','his','him'; ...
  'Jacob','he','his','him'; ...
  'Kevin','he','his','him'; ...
  'Lucas','he','his','him'; ...
  'Martin','he','his','him'; ...
  'Neil','he','his','him'; ...
  'Omar','he','his','him'; ...
  'Peter','he','his','him'; ...
  'Quentin','he','his','him'; ...
  'Ralph','he','his','him'; ...
  'Samuel','he','his','him'; ...
  'Ted','he','his','him'; ...
  'Ulysses','he','his','him'; ...
  'Vito','he','his','him'; ...
  'Wayne','he','his','him'; ...
  'Xander','he','his','him'; ...
  'Yancy','he','his','him'; ...
  'Zack','he','his','him'; ...
};

m_names3 = { ...
  'Arnold','he','his','him'; ...
  'Bill','he','his','him'; ...
  'Craig','he','his','him'; ...
  'Derek','he','his','him'; ...
  'Ernest','he','his','him'; ...
  'Felix','he','his','him'; ...
  'George','he','his','him'; ...
  'Herb','he','his','him'; ...
  'Irwin','he','his','him'; ...
  'Jarod','he','his','him'; ...
  'Keith','he','his','him'; ...
  'Lars','he','his','him'; ...
  'Mike','he','his','him'; ...
  'Nick','he','his','him'; ...
  'Oscar','he','his','him'; ...
  'Patrick','he','his','him'; ...
  'Quinlan','he','his','him'; ...
  'Rory','he','his','him'; ...
  'Scott','he','his','him'; ...
  'Trent','he','his','him'; ...
  'Umberto','he','his','him'; ...
  'Vincent','he','his','him'; ...
  'Warren','he','his','him'; ...
  'Xenon','he','his','him'; ...
  'Yarden','he','his','him'; ...
  'Zeke','he','his','him'; ...
};

fm_names = {f_names1,m_names1,f_names2,m_names2,f_names3,m_names3};
